name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip nodejs npm
        sudo npm install -g yarn pm2
        pip3 install -r requirements.txt
    - name: Build app
      run: |
        yarn install
        yarn build
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 65.108.20.32
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/NaijaTrading-dev/server
          pm2 start ecosystem.config.js
          cd /var/www/html
          rm -rf *
          cp -r $GITHUB_WORKSPACE/build/* .
          systemctl restart nginx
          
