name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        npm install
        npm install pm2 -g
        
    - name: Build app
      run: |
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 65.108.20.32
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          
          cd /root/NaijaTrading-dev/server
          pip install -r requirements.txt
          pm2 start ecosystem.config.js
          cd /var/www/html/react
          rm -rf *
          cp -r /root/NaijaTraiding-dev/client/build/* .
          systemctl restart nginx
          
