name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        cd client
        npm install
        npm run build
        cd ../server
        pip install -r requirements.txt
        
    - name: Build app
      run: |

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 65.108.20.32
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          pm2 delete all
          pm2 start server/application.py -- naijatrading
          cp -r /root/NaijaTrading-dev/client/build/* /var/www/html/react/
          systemctl restart nginx
          
