name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build app
      run: npm run build

    - name: Deploy to production
      if: github.ref == 'refs/heads/main'
      uses: my-actions/deploy-to-production@v1
      with:
        environment: production
        api-key: ${{ secrets.API_KEY }}
