name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        node-version: [16.x]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd client
        npm install
        cd ../server
        pip install -r requirements.txt
        
    - name: Build app
      run: |

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 65.108.20.32
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        prot: 22
        script: |
          cd NaijaTrading-dev
          git pull
          cd client
          npm prune
          npm install
          npm run build
          cp -r /root/NaijaTrading-dev/client/build/* /var/www/html/react/
          pm2 delete all
          pm2 start server/ecosystem.config.js
          systemctl restart nginx
          
