name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
 
    - name: Build app
      run: |
 
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 65.108.20.32
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/NaijaTrading-dev/client
          nvm use 16
          npm install
          npm run build
          cd /root/NaijaTrading-dev/server
          pip install -r requirements.txt
          pm2 delete all
          pm2 start ecosystem.config.js
          cp -r /root/NaijaTrading-dev/client/build/* /var/www/html/react/
          systemctl restart nginx
