name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install
        pip install -r requirements.txt

    - name: Build app
      run: |
        cd /root/NaijaTrading-dev/client
        npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: 65.108.20.32
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/NaijaTrading-dev/server
          pm2 delete all
          pm2 start ecosystem.config.js
          cp -r /root/NaijaTrading-dev/client/build/* /var/www/html/react/
          systemctl restart nginx
